# Generated by Django 5.1.6 on 2025-05-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edge',
            name='source',
        ),
        migrations.RemoveField(
            model_name='edge',
            name='target',
        ),
        migrations.AlterField(
            model_name='edge',
            name='data',
            field=models.JSONField(),
        ),
    ]
